// import image1 from "../assets/images/2224.jpg";
// import image2 from "../assets/images/10276.jpg";
// import image3 from "../assets/images/logo_make_11_06_2023_8.jpg";

// export interface SellerDetails {
//   id: string;
//   name: string;
//   image: string;
//   phoneNumber: string;
//   email: string;
//   company: string;
// }

// export interface PropertyDetails {
//   id: string;
//   name: string;
//   title: string;
//   description: string;
//   type: string;
//   bedrooms: number;
//   bathrooms: number;
//   furnishing: string;
//   constructionStatus: string;
//   listedBy: string;
//   superBuiltUpArea: number;
//   carpetArea: number;
//   totalFloors: number;
//   floorNo: number;
//   carParking: number;
//   facing: string;
//   projectName: string;
//   price: number;
//   postedDate: string;
//   images: string[];
//   location: string;
//   locationCoordinates: LocationCoordinates;
//   isFavorite: boolean;
//   sellerDetails: SellerDetails;
// }

// interface LocationCoordinates {
//   latitude: number;
//   longitude: number;
// }

// export const propertyDetails: PropertyDetails[] = [
//   {
//     id: "1001000100010088",
//     name: "Sunny Apartment",
//     title: "Apartment For Sale",
//     description: "Spacious apartment in Downtown with modern amenities.",
//     type: "Apartment",
//     bedrooms: 3,
//     bathrooms: 2,
//     furnishing: "Unfurnished",
//     constructionStatus: "Ready to move",
//     listedBy: "John Doe",
//     superBuiltUpArea: 1200,
//     carpetArea: 1000,
//     totalFloors: 15,
//     floorNo: 5,
//     carParking: 1,
//     facing: "East",
//     projectName: "Downtown Residency",
//     price: 500000,
//     postedDate: "2024-07-10",
//     images: [image1, image2, image3],
//     location: "Downtown, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.712776,
//       longitude: -74.005974,
//     },
//     sellerDetails: {
//       id: "seller1001",
//       name: "John Doe",
//       image: "https://www.example.com/images/john_doe.jpg",
//       phoneNumber: "123-456-7890",
//       email: "john.doe@example.com",
//       company: "Doe Realty",
//     },
//   },
//   {
//     id: "1002000200020002",
//     name: "Cozy Cottage",
//     title: "Apartment For Sale",
//     description: "Charming cottage in a quiet suburban neighborhood.",
//     type: "Independent House",
//     bedrooms: 2,
//     bathrooms: 1,
//     furnishing: "Semi-Furnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Jane Smith",
//     superBuiltUpArea: 900,
//     carpetArea: 800,
//     totalFloors: 1,
//     floorNo: 0,
//     carParking: 2,
//     facing: "North",
//     projectName: "Suburban Retreat",
//     price: 350000,
//     postedDate: "2024-06-20",
//     images: [image1, image2, image3],
//     location: "Suburbs, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.73061,
//       longitude: -73.935242,
//     },
//     sellerDetails: {
//       id: "seller1002",
//       name: "Jane Smith",
//       image: "https://www.example.com/images/jane_smith.jpg",
//       phoneNumber: "987-654-3210",
//       email: "jane.smith@example.com",
//       company: "Smith Realty",
//     },
//   },
//   {
//     id: "1003000330030003",
//     name: "Luxury Villa",
//     title: "Apartment For Sale",
//     description:
//       "Exquisite villa with luxurious amenities and panoramic views.",
//     type: "Villa",
//     bedrooms: 5,
//     bathrooms: 5,
//     furnishing: "Fully Furnished",
//     constructionStatus: "Under Construction",
//     listedBy: "Alice Johnson",
//     superBuiltUpArea: 3000,
//     carpetArea: 2500,
//     totalFloors: 2,
//     floorNo: 1,
//     carParking: 4,
//     facing: "South-East",
//     projectName: "Hilltop Haven",
//     price: 1200000,
//     postedDate: "2024-07-01",
//     images: [image1, image2, image3],
//     location: "Uptown, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.748817,
//       longitude: -73.985428,
//     },
//     sellerDetails: {
//       id: "seller1003",
//       name: "Alice Johnson",
//       image: "https://www.example.com/images/alice_johnson.jpg",
//       phoneNumber: "555-123-4567",
//       email: "alice.johnson@example.com",
//       company: "Johnson Realty",
//     },
//   },
//   {
//     id: "1004000400040004",
//     name: "Modern Loft",
//     title: "Apartment For Sale",
//     description:
//       "Stylish loft with contemporary design and city skyline views.",
//     type: "Penthouse",
//     bedrooms: 4,
//     bathrooms: 3,
//     furnishing: "Semi-Furnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Bob Brown",
//     superBuiltUpArea: 1500,
//     carpetArea: 1300,
//     totalFloors: 20,
//     floorNo: 15,
//     carParking: 2,
//     facing: "West",
//     projectName: "Skyline Heights",
//     price: 750000,
//     postedDate: "2024-07-05",
//     images: [image1, image2, image3],
//     location: "Midtown, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.754932,
//       longitude: -73.984016,
//     },
//     sellerDetails: {
//       id: "seller1004",
//       name: "Bob Brown",
//       image: "https://www.example.com/images/bob_brown.jpg",
//       phoneNumber: "111-222-3333",
//       email: "bob.brown@example.com",
//       company: "Brown Realty",
//     },
//   },
//   {
//     id: "1003000500050005",
//     name: "Beachside Bungalow",
//     title: "Apartment For Sale",
//     description:
//       "Serene bungalow with beachfront access and scenic surroundings.",
//     type: "Bungalow",
//     bedrooms: 3,
//     bathrooms: 2,
//     furnishing: "Unfurnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Charlie Davis",
//     superBuiltUpArea: 2000,
//     carpetArea: 1800,
//     totalFloors: 1,
//     floorNo: 0,
//     carParking: 3,
//     facing: "South-West",
//     projectName: "Beachside Retreat",
//     price: 950000,
//     postedDate: "2024-06-30",
//     images: [image1, image2, image3],
//     location: "Coastline, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.579021,
//       longitude: -74.151535,
//     },
//     sellerDetails: {
//       id: "seller1005",
//       name: "Charlie Davis",
//       image: "https://www.example.com/images/charlie_davis.jpg",
//       phoneNumber: "444-555-6666",
//       email: "charlie.davis@example.com",
//       company: "Davis Realty",
//     },
//   },
//   {
//     id: "1006000600060006",
//     name: "Downtown Studio",
//     title: "Apartment For Sale",
//     description:
//       "Compact studio in the heart of downtown with easy access to amenities.",
//     type: "Studio Apartment",
//     bedrooms: 1,
//     bathrooms: 1,
//     furnishing: "Fully Furnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Emily Evans",
//     superBuiltUpArea: 800,
//     carpetArea: 600,
//     totalFloors: 10,
//     floorNo: 7,
//     carParking: 1,
//     facing: "North-East",
//     projectName: "Downtown Towers",
//     price: 450000,
//     postedDate: "2024-07-07",
//     images: [image1, image2, image3],
//     location: "Downtown, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.707496,
//       longitude: -74.011276,
//     },
//     sellerDetails: {
//       id: "seller1006",
//       name: "Emily Evans",
//       image: "https://www.example.com/images/emily_evans.jpg",
//       phoneNumber: "777-888-9999",
//       email: "emily.evans@example.com",
//       company: "Evans Realty",
//     },
//   },
//   {
//     id: "1001000100010001",
//     name: "Sunny Apartment",
//     title: "Apartment For Sale",
//     description: "Spacious apartment in Downtown with modern amenities.",
//     type: "Apartment",
//     bedrooms: 3,
//     bathrooms: 2,
//     furnishing: "Unfurnished",
//     constructionStatus: "Ready to move",
//     listedBy: "John Doe",
//     superBuiltUpArea: 1200,
//     carpetArea: 1000,
//     totalFloors: 15,
//     floorNo: 5,
//     carParking: 1,
//     facing: "East",
//     projectName: "Downtown Residency",
//     price: 500000,
//     postedDate: "2024-07-10",
//     images: [image1, image2, image3],
//     location: "Downtown, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.712776,
//       longitude: -74.005974,
//     },
//     sellerDetails: {
//       id: "seller1001",
//       name: "John Doe",
//       image: "https://www.example.com/images/john_doe.jpg",
//       phoneNumber: "123-456-7890",
//       email: "john.doe@example.com",
//       company: "Doe Realty",
//     },
//   },
//   {
//     id: "2002000200020002",
//     name: "Cozy Cottage",
//     title: "Independent House For Sale",
//     description: "Charming cottage in a quiet suburban neighborhood.",
//     type: "Independent House",
//     bedrooms: 2,
//     bathrooms: 1,
//     furnishing: "Semi-Furnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Jane Smith",
//     superBuiltUpArea: 900,
//     carpetArea: 800,
//     totalFloors: 1,
//     floorNo: 0,
//     carParking: 2,
//     facing: "North",
//     projectName: "Suburban Retreat",
//     price: 350000,
//     postedDate: "2024-06-20",
//     images: [image1, image2, image3],
//     location: "Suburbs, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.73061,
//       longitude: -73.935242,
//     },
//     sellerDetails: {
//       id: "seller1002",
//       name: "Jane Smith",
//       image: "https://www.example.com/images/jane_smith.jpg",
//       phoneNumber: "987-654-3210",
//       email: "jane.smith@example.com",
//       company: "Smith Realty",
//     },
//   },
//   {
//     id: "1003000300030003",
//     name: "Luxury Villa",
//     title: "Villa For Sale",
//     description:
//       "Exquisite villa with luxurious amenities and panoramic views.",
//     type: "Villa",
//     bedrooms: 5,
//     bathrooms: 5,
//     furnishing: "Fully Furnished",
//     constructionStatus: "Under Construction",
//     listedBy: "Alice Johnson",
//     superBuiltUpArea: 3000,
//     carpetArea: 2500,
//     totalFloors: 2,
//     floorNo: 1,
//     carParking: 4,
//     facing: "South-East",
//     projectName: "Hilltop Haven",
//     price: 1200000,
//     postedDate: "2024-07-01",
//     images: [image1, image2, image3],
//     location: "Uptown, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.748817,
//       longitude: -73.985428,
//     },
//     sellerDetails: {
//       id: "seller1003",
//       name: "Alice Johnson",
//       image: "https://www.example.com/images/alice_johnson.jpg",
//       phoneNumber: "555-123-4567",
//       email: "alice.johnson@example.com",
//       company: "Johnson Realty",
//     },
//   },
//   {
//     id: "1004000400040056",
//     name: "Modern Loft",
//     title: "Penthouse For Sale",
//     description:
//       "Stylish loft with contemporary design and city skyline views.",
//     type: "Penthouse",
//     bedrooms: 4,
//     bathrooms: 3,
//     furnishing: "Semi-Furnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Bob Brown",
//     superBuiltUpArea: 1500,
//     carpetArea: 1300,
//     totalFloors: 20,
//     floorNo: 15,
//     carParking: 2,
//     facing: "West",
//     projectName: "Skyline Heights",
//     price: 750000,
//     postedDate: "2024-07-05",
//     images: [image1, image2, image3],
//     location: "Midtown, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.754932,
//       longitude: -73.984016,
//     },
//     sellerDetails: {
//       id: "seller1004",
//       name: "Bob Brown",
//       image: "https://www.example.com/images/bob_brown.jpg",
//       phoneNumber: "111-222-3333",
//       email: "bob.brown@example.com",
//       company: "Brown Realty",
//     },
//   },
//   {
//     id: "1005000500050005",
//     name: "Beachside Bungalow",
//     title: "Bungalow For Sale",
//     description:
//       "Serene bungalow with beachfront access and scenic surroundings.",
//     type: "Bungalow",
//     bedrooms: 3,
//     bathrooms: 2,
//     furnishing: "Unfurnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Charlie Davis",
//     superBuiltUpArea: 2000,
//     carpetArea: 1800,
//     totalFloors: 1,
//     floorNo: 0,
//     carParking: 3,
//     facing: "South-West",
//     projectName: "Beachside Retreat",
//     price: 950000,
//     postedDate: "2024-06-30",
//     images: [image1, image2, image3],
//     location: "Coastline, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.579021,
//       longitude: -74.151535,
//     },
//     sellerDetails: {
//       id: "seller1005",
//       name: "Charlie Davis",
//       image: "https://www.example.com/images/charlie_davis.jpg",
//       phoneNumber: "444-555-6666",
//       email: "charlie.davis@example.com",
//       company: "Davis Realty",
//     },
//   },
//   {
//     id: "1006000600090006",
//     name: "Downtown Studio",
//     title: "Studio Apartment For Sale",
//     description:
//       "Compact studio in the heart of downtown with easy access to amenities.",
//     type: "Studio Apartment",
//     bedrooms: 1,
//     bathrooms: 1,
//     furnishing: "Fully Furnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Emily Evans",
//     superBuiltUpArea: 800,
//     carpetArea: 600,
//     totalFloors: 10,
//     floorNo: 7,
//     carParking: 1,
//     facing: "North-East",
//     projectName: "Downtown Towers",
//     price: 450000,
//     postedDate: "2024-07-07",
//     images: [image1, image2, image3],
//     location: "Downtown, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.707496,
//       longitude: -74.011276,
//     },
//     sellerDetails: {
//       id: "seller1006",
//       name: "Emily Evans",
//       image: "https://www.example.com/images/emily_evans.jpg",
//       phoneNumber: "777-888-9999",
//       email: "emily.evans@example.com",
//       company: "Evans Realty",
//     },
//   },
//   {
//     id: "1007000700070007",
//     name: "Urban Condo",
//     title: "Condo For Sale",
//     description: "Modern condo with urban lifestyle and amenities.",
//     type: "Condo",
//     bedrooms: 2,
//     bathrooms: 2,
//     furnishing: "Semi-Furnished",
//     constructionStatus: "Ready to move",
//     listedBy: "David Clark",
//     superBuiltUpArea: 1000,
//     carpetArea: 850,
//     totalFloors: 12,
//     floorNo: 8,
//     carParking: 1,
//     facing: "South",
//     projectName: "Urban Living Complex",
//     price: 600000,
//     postedDate: "2024-07-12",
//     images: [image1, image2, image3],
//     location: "City Center, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.743798,
//       longitude: -73.992298,
//     },
//     sellerDetails: {
//       id: "seller1007",
//       name: "David Clark",
//       image: "https://www.example.com/images/david_clark.jpg",
//       phoneNumber: "999-555-4444",
//       email: "david.clark@example.com",
//       company: "Clark Realty",
//     },
//   },
//   {
//     id: "1008000800080008",
//     name: "Suburban House",
//     title: "House For Sale",
//     description: "Cozy house in a peaceful suburban area.",
//     type: "House",
//     bedrooms: 3,
//     bathrooms: 2,
//     furnishing: "Unfurnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Susan Lee",
//     superBuiltUpArea: 1400,
//     carpetArea: 1200,
//     totalFloors: 2,
//     floorNo: 1,
//     carParking: 2,
//     facing: "West",
//     projectName: "Suburban Bliss",
//     price: 550000,
//     postedDate: "2024-06-25",
//     images: [image1, image2, image3],
//     location: "Suburbs, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.721776,
//       longitude: -73.965974,
//     },
//     sellerDetails: {
//       id: "seller1008",
//       name: "Susan Lee",
//       image: "https://www.example.com/images/susan_lee.jpg",
//       phoneNumber: "123-555-7890",
//       email: "susan.lee@example.com",
//       company: "Lee Realty",
//     },
//   },
//   {
//     id: "1009000900090009",
//     name: "Countryside Farmhouse",
//     title: "Farmhouse For Sale",
//     description: "Beautiful farmhouse with ample land and scenic views.",
//     type: "Farmhouse",
//     bedrooms: 4,
//     bathrooms: 3,
//     furnishing: "Fully Furnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Mike Johnson",
//     superBuiltUpArea: 2000,
//     carpetArea: 1800,
//     totalFloors: 1,
//     floorNo: 0,
//     carParking: 3,
//     facing: "East",
//     projectName: "Countryside Retreat",
//     price: 700000,
//     postedDate: "2024-06-15",
//     images: [image1, image2, image3],
//     location: "Countryside, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.762776,
//       longitude: -73.975974,
//     },
//     sellerDetails: {
//       id: "seller1009",
//       name: "Mike Johnson",
//       image: "https://www.example.com/images/mike_johnson.jpg",
//       phoneNumber: "321-456-7890",
//       email: "mike.johnson@example.com",
//       company: "Johnson Realty",
//     },
//   },
//   {
//     id: "1010001000100010",
//     name: "Mountain Cabin",
//     title: "Cabin For Sale",
//     description: "Rustic cabin with mountain views and serene surroundings.",
//     type: "Cabin",
//     bedrooms: 2,
//     bathrooms: 1,
//     furnishing: "Fully Furnished",
//     constructionStatus: "Ready to move",
//     listedBy: "Linda White",
//     superBuiltUpArea: 800,
//     carpetArea: 700,
//     totalFloors: 1,
//     floorNo: 0,
//     carParking: 1,
//     facing: "North",
//     projectName: "Mountain Retreat",
//     price: 300000,
//     postedDate: "2024-06-05",
//     images: [image1, image2, image3],
//     location: "Mountains, Cityville",
//     isFavorite: false,
//     locationCoordinates: {
//       latitude: 40.782776,
//       longitude: -73.995974,
//     },
//     sellerDetails: {
//       id: "seller1010",
//       name: "Linda White",
//       image: "https://www.example.com/images/linda_white.jpg",
//       phoneNumber: "123-999-7890",
//       email: "linda.white@example.com",
//       company: "White Realty",
//     },
//   },
// ];
import React from 'react'

const propertyListing2 = () => {
  return (
    <div>propertyListing2</div>
  )
}

export default propertyListing2