export const propertyDetails = [
  {
    id: "1001000100010001",
    name: "Sunny Apartment",
    description: "Spacious apartment in Downtown with modern amenities.",
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Unfurnished",
    constructionStatus: "Ready to move",
    listedBy: "John Doe",
    superBuiltupArea: 1200,
    carpetArea: 1000,
    totalFloors: 15,
    floorNo: 5,
    carParking: 1,
    facing: "East",
    projectName: "Downtown Residency",
    price: 500000,
    postedDate: "2024-07-10",
    image: "https://via.placeholder.com/300x200",
    location: "Downtown, Cityville",
    locationCoordinates: {
      latitude: 40.712776,
      longitude: -74.005974,
    },
  },
  {
    id: "1002000200020002",
    name: "Cozy Cottage",
    description: "Charming cottage in a quiet suburban neighborhood.",
    type: "Independent House",
    bedrooms: 2,
    bathrooms: 1,
    furnishing: "Semi-Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Jane Smith",
    superBuiltupArea: 900,
    carpetArea: 800,
    totalFloors: 1,
    floorNo: "Ground",
    carParking: 2,
    facing: "North",
    projectName: "Suburban Retreat",
    price: 350000,
    postedDate: "2024-06-20",
    image: "https://via.placeholder.com/300x200",
    location: "Suburbs, Cityville",
    locationCoordinates: {
      latitude: 40.73061,
      longitude: -73.935242,
    },
  },
  {
    id: "1003000300030003",
    name: "Luxury Villa",
    description:
      "Exquisite villa with luxurious amenities and panoramic views.",
    type: "Villa",
    bedrooms: 5,
    bathrooms: 5,
    furnishing: "Fully Furnished",
    constructionStatus: "Under Construction",
    listedBy: "Alice Johnson",
    superBuiltupArea: 3000,
    carpetArea: 2500,
    totalFloors: 2,
    floorNo: "Ground + 1",
    carParking: 4,
    facing: "South-East",
    projectName: "Hilltop Haven",
    price: 1200000,
    postedDate: "2024-07-01",
    image: "https://via.placeholder.com/300x200",
    location: "Uptown, Cityville",
    locationCoordinates: {
      latitude: 40.748817,
      longitude: -73.985428,
    },
  },
  {
    id: "1004000400040004",
    name: "Modern Loft",
    description:
      "Stylish loft with contemporary design and city skyline views.",
    type: "Penthouse",
    bedrooms: 4,
    bathrooms: 3,
    furnishing: "Semi-Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Bob Brown",
    superBuiltupArea: 1500,
    carpetArea: 1300,
    totalFloors: 20,
    floorNo: 15,
    carParking: 2,
    facing: "West",
    projectName: "Skyline Heights",
    price: 750000,
    postedDate: "2024-07-05",
    image: "https://via.placeholder.com/300x200",
    location: "Midtown, Cityville",
    locationCoordinates: {
      latitude: 40.754932,
      longitude: -73.984016,
    },
  },
  {
    id: "1005000500050005",
    name: "Beachside Bungalow",
    description:
      "Serene bungalow with beachfront access and scenic surroundings.",
    type: "Bungalow",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Unfurnished",
    constructionStatus: "Ready to move",
    listedBy: "Charlie Davis",
    superBuiltupArea: 2000,
    carpetArea: 1800,
    totalFloors: 1,
    floorNo: "Ground",
    carParking: 3,
    facing: "South-West",
    projectName: "Beachside Retreat",
    price: 950000,
    postedDate: "2024-06-30",
    image: "https://via.placeholder.com/300x200",
    location: "Coastline, Cityville",
    locationCoordinates: {
      latitude: 40.579021,
      longitude: -74.151535,
    },
  },
  {
    id: "1006000600060006",
    name: "Downtown Studio",
    description:
      "Compact studio in the heart of downtown with easy access to amenities.",
    type: "Studio Apartment",
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "Fully Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Emily Evans",
    superBuiltupArea: 800,
    carpetArea: 600,
    totalFloors: 10,
    floorNo: 7,
    carParking: 1,
    facing: "North-East",
    projectName: "Downtown Towers",
    price: 450000,
    postedDate: "2024-07-07",
    image: "https://via.placeholder.com/300x200",
    location: "Downtown, Cityville",
    locationCoordinates: {
      latitude: 40.707496,
      longitude: -74.011276,
    },
  },
  {
    id: "1007000700070007",
    name: "Penthouse Suite",
    description:
      "Opulent penthouse offering unparalleled luxury and breathtaking city views.",
    type: "Penthouse",
    bedrooms: 6,
    bathrooms: 5,
    furnishing: "Fully Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Frank Green",
    superBuiltupArea: 4000,
    carpetArea: 3500,
    totalFloors: 30,
    floorNo: 28,
    carParking: 4,
    facing: "North-West",
    projectName: "Skyline Splendor",
    price: 2000000,
    postedDate: "2024-07-03",
    image: "https://via.placeholder.com/300x200",
    location: "Skyscraper District, Cityville",
    locationCoordinates: {
      latitude: 40.748541,
      longitude: -73.985758,
    },
  },
  {
    id: "1008000800080008",
    name: "Country House",
    description:
      "Tranquil country house surrounded by lush greenery and peaceful ambiance.",
    type: "Farmhouse",
    bedrooms: 4,
    bathrooms: 3,
    furnishing: "Semi-Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Grace Hall",
    superBuiltupArea: 2500,
    carpetArea: 2000,
    totalFloors: 2,
    floorNo: "Ground + 1",
    carParking: 2,
    facing: "East",
    projectName: "Green Haven Farms",
    price: 600000,
    postedDate: "2024-07-08",
    image: "https://via.placeholder.com/300x200",
    location: "Countryside, Cityville",
    locationCoordinates: {
      latitude: 40.780368,
      longitude: -73.977426,
    },
  },
  {
    id: "1009000900090009",
    name: "Suburban Home",
    description:
      "Comfortable suburban home with modern amenities and spacious interiors.",
    type: "Villa",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Unfurnished",
    constructionStatus: "Ready to move",
    listedBy: "Hank Ives",
    superBuiltupArea: 1800,
    carpetArea: 1500,
    totalFloors: 2,
    floorNo: "Ground + 1",
    carParking: 2,
    facing: "South",
    projectName: "Suburban Serenity",
    price: 700000,
    postedDate: "2024-07-02",
    image: "https://via.placeholder.com/300x200",
    location: "Suburban Area, Cityville",
    locationCoordinates: {
      latitude: 40.732253,
      longitude: -73.993318,
    },
  },
  {
    id: "1010001000010000",
    name: "Riverside Cabin",
    description:
      "Quaint cabin by the river, ideal for nature lovers seeking a peaceful retreat.",
    type: "Cabin",
    bedrooms: 2,
    bathrooms: 1,
    furnishing: "Semi-Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Ivy Jackson",
    superBuiltupArea: 1000,
    carpetArea: 800,
    totalFloors: 1,
    floorNo: "Ground",
    carParking: 1,
    facing: "West",
    projectName: "Riverside Haven",
    price: 300000,
    postedDate: "2024-07-04",
    image: "https://via.placeholder.com/300x200",
    location: "Riverbank, Cityville",
    locationCoordinates: {
      latitude: 40.706192,
      longitude: -74.00916,
    },
  },
];
