import image1 from "../../assets/images/2224.jpg";
import image2 from "../../assets/images/10276.jpg";
import image3 from "../../assets/images/logo_make_11_06_2023_8.jpg";
import LandlordProfileImage from "../../assets/images/images.jpeg";
import { PropertyDetails } from "./PropertiesForBuy";

export const propertiesForRent: PropertyDetails[] = [
  {
    id: "2002000200020099",
    name: "Cozy Loft",
    title: "Loft For Rent",
    description:
      "Charming loft in the heart of the city with easy access to public transport.",
    type: "Loft",
    bedrooms: 2,
    bathrooms: 1,
    furnishing: "Furnished",
    constructionStatus: "Newly renovated",
    listedBy: "Eve Adams",
    superBuiltUpArea: 850,
    carpetArea: 700,
    totalFloors: 8,
    floorNo: 3,
    carParking: 0,
    facing: "North",
    projectName: "City Loft Complex",
    price: 1500,
    postedDate: "2024-07-20",
    images: [image1, image2, image3],
    location: "City Center, Metropolis",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.73061,
      longitude: -73.935242,
    },
    sellerDetails: {
      id: "seller-2001",
      fullName: "Eve Adams",
      username: "eve_adams",
      email: "eve.adams@realestate.com",
      role: "Landlord",
      propertiesListed: 10,
      contactNumber: "+1234567892",
      address: "789 Elm Street, Metropolis, NY, USA",
      profilePicture: LandlordProfileImage,
      verified: true,
      rating: 4.6,
      lastLogin: new Date("2024-07-22T09:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/eveadams",
        facebook: "https://facebook.com/eveadams",
      },
      preferredContactMethod: "email",
      bio: "Experienced landlord with a portfolio of well-maintained rental properties.",
      certifications: ["Certified Property Manager"],
      createdAt: new Date("2023-12-01T09:00:00Z"),
      updatedAt: new Date("2024-07-22T09:00:00Z"),
    },
    reviews: [
      {
        id: "review2001",
        reviewerName: "James Brown",
        dateTime: "2024-07-20T10:00:00",
        rating: 4.0,
        description:
          "Great loft with a modern design. Convenient location and well-furnished.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2002",
        reviewerName: "Linda Green",
        dateTime: "2024-07-22T11:30:00",
        rating: 4.5,
        description:
          "The loft is cozy and nicely decorated. The neighborhood is lively and full of amenities.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2003",
        reviewerName: "Michael Smith",
        dateTime: "2024-07-23T16:45:00",
        rating: 3.8,
        description:
          "Good place overall, but the noise from the street can be a bit disruptive.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2004",
        reviewerName: "Sarah Jones",
        dateTime: "2024-07-25T14:00:00",
        rating: 5.0,
        description:
          "Perfect loft with excellent amenities. The landlord was very responsive and helpful.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "2002000200020100",
    name: "Modern Studio",
    title: "Studio For Rent",
    description:
      "Compact and modern studio with high-end appliances and great city views.",
    type: "Studio",
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "Furnished",
    constructionStatus: "New",
    listedBy: "Mark Lee",
    superBuiltUpArea: 500,
    carpetArea: 450,
    totalFloors: 12,
    floorNo: 7,
    carParking: 1,
    facing: "West",
    projectName: "Skyline Studios",
    price: 1200,
    postedDate: "2024-07-21",
    images: [image1, image2, image3],
    location: "Skyline Towers, Metropolis",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.743895,
      longitude: -73.971394,
    },
    sellerDetails: {
      id: "seller-2002",
      fullName: "Mark Lee",
      username: "mark_lee",
      email: "mark.lee@realestate.com",
      role: "Landlord",
      propertiesListed: 8,
      contactNumber: "+1234567893",
      address: "123 Maple Lane, Metropolis, NY, USA",
      profilePicture: LandlordProfileImage,
      verified: true,
      rating: 4.4,
      lastLogin: new Date("2024-07-21T09:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/marklee",
        facebook: "https://facebook.com/marklee",
      },
      preferredContactMethod: "email",
      bio: "Professional landlord with a keen eye for detail and tenant satisfaction.",
      certifications: ["Certified Rental Manager"],
      createdAt: new Date("2023-10-01T09:00:00Z"),
      updatedAt: new Date("2024-07-21T09:00:00Z"),
    },
    reviews: [
      {
        id: "review2005",
        reviewerName: "Natalie Clark",
        dateTime: "2024-07-22T10:30:00",
        rating: 4.2,
        description:
          "A stylish studio with excellent amenities. The view is impressive and the space is well-organized.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2006",
        reviewerName: "Tom Wilson",
        dateTime: "2024-07-23T12:00:00",
        rating: 4.0,
        description:
          "Modern and clean, but a bit noisy at night. Overall a good experience.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "2002000200020101",
    name: "Spacious Duplex",
    title: "Duplex For Rent",
    description:
      "Elegant duplex with two floors, perfect for a family. Includes a private garden.",
    type: "Duplex",
    bedrooms: 4,
    bathrooms: 3,
    furnishing: "Partially furnished",
    constructionStatus: "Recently renovated",
    listedBy: "Sophia Turner",
    superBuiltUpArea: 2200,
    carpetArea: 2000,
    totalFloors: 2,
    floorNo: 1,
    carParking: 2,
    facing: "South",
    projectName: "Greenfield Residences",
    price: 2500,
    postedDate: "2024-07-22",
    images: [image1, image2, image3],
    location: "Greenfield, Metropolis",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.75,
      longitude: -73.985,
    },
    sellerDetails: {
      id: "seller-2003",
      fullName: "Sophia Turner",
      username: "sophia_turner",
      email: "sophia.turner@realestate.com",
      role: "Landlord",
      propertiesListed: 5,
      contactNumber: "+1234567894",
      address: "456 Birch Street, Metropolis, NY, USA",
      profilePicture: LandlordProfileImage,
      verified: true,
      rating: 4.7,
      lastLogin: new Date("2024-07-22T10:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/sophiaturner",
        facebook: "https://facebook.com/sophiaturner",
      },
      preferredContactMethod: "phone",
      bio: "Landlord with a focus on family-friendly properties and customer satisfaction.",
      certifications: ["Certified Property Consultant"],
      createdAt: new Date("2023-11-15T09:00:00Z"),
      updatedAt: new Date("2024-07-22T09:00:00Z"),
    },
    reviews: [
      {
        id: "review2007",
        reviewerName: "Linda Scott",
        dateTime: "2024-07-22T14:00:00",
        rating: 5.0,
        description:
          "Fantastic duplex with plenty of space. The garden is a great bonus for families.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2008",
        reviewerName: "Daniel Walker",
        dateTime: "2024-07-23T16:30:00",
        rating: 4.5,
        description:
          "Great property in a quiet neighborhood. The landlord is very accommodating.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "2002000200020102",
    name: "Chic Penthouse",
    title: "Penthouse For Rent",
    description:
      "Luxurious penthouse with panoramic city views and high-end finishes.",
    type: "Penthouse",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Furnished",
    constructionStatus: "New",
    listedBy: "Robert Black",
    superBuiltUpArea: 3000,
    carpetArea: 2800,
    totalFloors: 1,
    floorNo: 12,
    carParking: 3,
    facing: "East",
    projectName: "Skyline Heights",
    price: 6000,
    postedDate: "2024-07-23",
    images: [image1, image2, image3],
    location: "Uptown, Metropolis",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.755,
      longitude: -73.976,
    },
    sellerDetails: {
      id: "seller-2004",
      fullName: "Robert Black",
      username: "robert_black",
      email: "robert.black@realestate.com",
      role: "Landlord",
      propertiesListed: 3,
      contactNumber: "+1234567895",
      address: "321 Pine Street, Metropolis, NY, USA",
      profilePicture: LandlordProfileImage,
      verified: true,
      rating: 4.8,
      lastLogin: new Date("2024-07-23T11:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/robertblack",
        facebook: "https://facebook.com/robertblack",
      },
      preferredContactMethod: "phone",
      bio: "Specializes in high-end properties with exceptional amenities and customer service.",
      certifications: ["Luxury Property Specialist"],
      createdAt: new Date("2024-01-10T09:00:00Z"),
      updatedAt: new Date("2024-07-23T09:00:00Z"),
    },
    reviews: [
      {
        id: "review2009",
        reviewerName: "Emma Green",
        dateTime: "2024-07-23T09:30:00",
        rating: 5.0,
        description:
          "Incredible penthouse with breathtaking views. The interiors are top-notch.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2010",
        reviewerName: "Oliver Adams",
        dateTime: "2024-07-24T13:00:00",
        rating: 4.8,
        description:
          "The best penthouse experience I’ve had. Worth every penny!",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "2002000200020103",
    name: "Classic Townhouse",
    title: "Townhouse For Rent",
    description:
      "Elegant townhouse with classic design elements and modern conveniences.",
    type: "Townhouse",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Partially furnished",
    constructionStatus: "Well-maintained",
    listedBy: "James White",
    superBuiltUpArea: 1800,
    carpetArea: 1600,
    totalFloors: 3,
    floorNo: 1,
    carParking: 2,
    facing: "South",
    projectName: "Heritage Townhomes",
    price: 2200,
    postedDate: "2024-07-24",
    images: [image1, image2, image3],
    location: "Heritage Park, Metropolis",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.742,
      longitude: -73.979,
    },
    sellerDetails: {
      id: "seller-2005",
      fullName: "James White",
      username: "james_white",
      email: "james.white@realestate.com",
      role: "Landlord",
      propertiesListed: 7,
      contactNumber: "+1234567896",
      address: "654 Cedar Avenue, Metropolis, NY, USA",
      profilePicture: LandlordProfileImage,
      verified: true,
      rating: 4.3,
      lastLogin: new Date("2024-07-24T10:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/jameswhite",
        facebook: "https://facebook.com/jameswhite",
      },
      preferredContactMethod: "email",
      bio: "Landlord with a focus on classic design properties and high tenant satisfaction.",
      certifications: ["Certified Home Stager"],
      createdAt: new Date("2023-08-10T09:00:00Z"),
      updatedAt: new Date("2024-07-24T09:00:00Z"),
    },
    reviews: [
      {
        id: "review2011",
        reviewerName: "Sophia Brown",
        dateTime: "2024-07-24T12:00:00",
        rating: 4.8,
        description:
          "Beautiful townhouse with a charming design. The landlord was very accommodating.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2012",
        reviewerName: "Liam Harris",
        dateTime: "2024-07-25T14:00:00",
        rating: 4.5,
        description:
          "Great location and well-kept property. The classic style is very appealing.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "2002000200020104",
    name: "Elegant Condo",
    title: "Condo For Rent",
    description:
      "Modern condo with elegant finishes and access to community amenities.",
    type: "Condo",
    bedrooms: 2,
    bathrooms: 2,
    furnishing: "Fully furnished",
    constructionStatus: "Newly built",
    listedBy: "Olivia Davis",
    superBuiltUpArea: 1200,
    carpetArea: 1100,
    totalFloors: 10,
    floorNo: 5,
    carParking: 1,
    facing: "East",
    projectName: "Sunrise Condominiums",
    price: 1700,
    postedDate: "2024-07-25",
    images: [image1, image2, image3],
    location: "Sunrise Valley, Metropolis",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.758,
      longitude: -73.98,
    },
    sellerDetails: {
      id: "seller-2006",
      fullName: "Olivia Davis",
      username: "olivia_davis",
      email: "olivia.davis@realestate.com",
      role: "Landlord",
      propertiesListed: 6,
      contactNumber: "+1234567897",
      address: "987 Birchwood Drive, Metropolis, NY, USA",
      profilePicture: LandlordProfileImage,
      verified: true,
      rating: 4.6,
      lastLogin: new Date("2024-07-25T11:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/oliviadavis",
        facebook: "https://facebook.com/oliviadavis",
      },
      preferredContactMethod: "email",
      bio: "Dedicated landlord with properties that offer modern conveniences and style.",
      certifications: ["Certified Property Owner"],
      createdAt: new Date("2023-09-01T09:00:00Z"),
      updatedAt: new Date("2024-07-25T09:00:00Z"),
    },
    reviews: [
      {
        id: "review2013",
        reviewerName: "Ethan Johnson",
        dateTime: "2024-07-25T09:00:00",
        rating: 4.7,
        description:
          "The condo is stylish and well-maintained. Great amenities and responsive landlord.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2014",
        reviewerName: "Ava Smith",
        dateTime: "2024-07-26T13:00:00",
        rating: 4.4,
        description:
          "Very pleased with the condo. The only downside is the limited parking space.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "2002000200020105",
    name: "Sunny Apartment",
    title: "Apartment For Rent",
    description:
      "Bright apartment with large windows and modern finishes, ideal for city living.",
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 1,
    furnishing: "Unfurnished",
    constructionStatus: "Newly renovated",
    listedBy: "Daniel Walker",
    superBuiltUpArea: 1000,
    carpetArea: 900,
    totalFloors: 6,
    floorNo: 4,
    carParking: 1,
    facing: "North",
    projectName: "City Light Apartments",
    price: 1400,
    postedDate: "2024-07-26",
    images: [image1, image2, image3],
    location: "Downtown, Metropolis",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.7425,
      longitude: -73.9875,
    },
    sellerDetails: {
      id: "seller-2007",
      fullName: "Daniel Walker",
      username: "daniel_walker",
      email: "daniel.walker@realestate.com",
      role: "Landlord",
      propertiesListed: 9,
      contactNumber: "+1234567898",
      address: "321 Elm Street, Metropolis, NY, USA",
      profilePicture: LandlordProfileImage,
      verified: true,
      rating: 4.4,
      lastLogin: new Date("2024-07-26T10:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/danielwalker",
        facebook: "https://facebook.com/danielwalker",
      },
      preferredContactMethod: "phone",
      bio: "Landlord with a diverse portfolio of residential properties in prime locations.",
      certifications: ["Certified Rental Property Owner"],
      createdAt: new Date("2023-10-20T09:00:00Z"),
      updatedAt: new Date("2024-07-26T09:00:00Z"),
    },
    reviews: [
      {
        id: "review2015",
        reviewerName: "Mia Brown",
        dateTime: "2024-07-26T11:00:00",
        rating: 4.3,
        description:
          "Nice apartment with a great location. The landlord was very helpful.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2016",
        reviewerName: "Jacob Wilson",
        dateTime: "2024-07-27T14:00:00",
        rating: 4.1,
        description:
          "Overall a good rental experience. The apartment is well-maintained but could use some upgrades.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "2002000200020106",
    name: "Urban Retreat",
    title: "Apartment For Rent",
    description:
      "Modern apartment with upscale features and a convenient location near the city center.",
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Fully furnished",
    constructionStatus: "New",
    listedBy: "Ella Carter",
    superBuiltUpArea: 1500,
    carpetArea: 1400,
    totalFloors: 8,
    floorNo: 6,
    carParking: 2,
    facing: "West",
    projectName: "Central Urban Apartments",
    price: 2200,
    postedDate: "2024-07-27",
    images: [image1, image2, image3],
    location: "Central Park, Metropolis",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.748817,
      longitude: -73.985428,
    },
    sellerDetails: {
      id: "seller-2008",
      fullName: "Ella Carter",
      username: "ella_carter",
      email: "ella.carter@realestate.com",
      role: "Landlord",
      propertiesListed: 4,
      contactNumber: "+1234567899",
      address: "234 Maple Street, Metropolis, NY, USA",
      profilePicture: LandlordProfileImage,
      verified: true,
      rating: 4.7,
      lastLogin: new Date("2024-07-27T10:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/ellacarter",
        facebook: "https://facebook.com/ellacarter",
      },
      preferredContactMethod: "email",
      bio: "Landlord with a focus on modern, upscale apartments in prime locations.",
      certifications: ["Certified Urban Property Specialist"],
      createdAt: new Date("2023-12-05T09:00:00Z"),
      updatedAt: new Date("2024-07-27T09:00:00Z"),
    },
    reviews: [
      {
        id: "review2017",
        reviewerName: "Lucas Martinez",
        dateTime: "2024-07-27T12:00:00",
        rating: 4.6,
        description:
          "Fantastic apartment with great features. The location is very convenient.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2018",
        reviewerName: "Isabella Lopez",
        dateTime: "2024-07-28T13:00:00",
        rating: 4.4,
        description:
          "Very pleased with the apartment. It’s modern and well-maintained.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "2002000200020107",
    name: "Quiet Cottage",
    title: "Cottage For Rent",
    description:
      "Charming cottage with a peaceful environment, perfect for a retreat from the city.",
    type: "Cottage",
    bedrooms: 2,
    bathrooms: 1,
    furnishing: "Partially furnished",
    constructionStatus: "Well-maintained",
    listedBy: "Henry Lee",
    superBuiltUpArea: 900,
    carpetArea: 800,
    totalFloors: 1,
    floorNo: 1,
    carParking: 1,
    facing: "North",
    projectName: "Woodland Retreat",
    price: 1300,
    postedDate: "2024-07-28",
    images: [image1, image2, image3],
    location: "Woodland Hills, Metropolis",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.73,
      longitude: -73.93,
    },
    sellerDetails: {
      id: "seller-2009",
      fullName: "Henry Lee",
      username: "henry_lee",
      email: "henry.lee@realestate.com",
      role: "Landlord",
      propertiesListed: 2,
      contactNumber: "+1234567800",
      address: "987 Willow Lane, Metropolis, NY, USA",
      profilePicture: LandlordProfileImage,
      verified: true,
      rating: 4.5,
      lastLogin: new Date("2024-07-28T09:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/henrylee",
        facebook: "https://facebook.com/henrylee",
      },
      preferredContactMethod: "phone",
      bio: "Landlord specializing in serene properties with a focus on peaceful living.",
      certifications: ["Certified Cottage Specialist"],
      createdAt: new Date("2024-01-15T09:00:00Z"),
      updatedAt: new Date("2024-07-28T09:00:00Z"),
    },
    reviews: [
      {
        id: "review2019",
        reviewerName: "Natalie Davis",
        dateTime: "2024-07-28T10:00:00",
        rating: 4.7,
        description:
          "The cottage is lovely and provides a peaceful escape from the city. The landlord was very friendly.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review2020",
        reviewerName: "Ethan Lee",
        dateTime: "2024-07-29T12:00:00",
        rating: 4.5,
        description: "Cozy and charming cottage. Ideal for a relaxing getaway.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
];
