import image1 from "../../../assets/images/2224.jpg";
import image2 from "../../../assets/images/10276.jpg";
import image3 from "../../../assets/images/logo_make_11_06_2023_8.jpg";
import SellerProfileImage from "../../../assets/images/images.jpeg";

export interface SellerDetails {
  id: string;
  firstName: string;
  lastName: string;
  username: string;
  email: string;
  role: string;
  propertiesListed: number;
  contactNumber: string;
  address: string;
  profilePicture: string;
  verified: boolean;
  rating?: number;
  lastLogin?: Date;
  socialLinks?: { [key: string]: string };
  preferredContactMethod?: string;
  bio?: string;
  certifications?: string[];
  firmName?: string; // Name of the firm the seller is associated with
  createdAt: Date;
  updatedAt: Date;
}

export interface PropertyDetails {
  id: string;
  name: string;
  title: string;
  description: string;
  type: string;
  bedrooms: number;
  bathrooms: number;
  furnishing: string;
  constructionStatus: string;
  listedBy: string;
  superBuiltUpArea: number;
  carpetArea: number;
  totalFloors: number;
  floorNo: number;
  carParking: number;
  facing: string;
  projectName: string;
  price: number;
  postedDate: string;
  images: any;
  location: string;
  locationCoordinates: LocationCoordinates;
  isFavorite: boolean;
  sellerDetails: SellerDetails;
  reviews: ReviewDetails[];
}

export interface ReviewDetails {
  id: string;
  reviewerName: string;
  dateTime: string;
  rating: number;
  description: string;
  image: string;
}

interface LocationCoordinates {
  latitude: number;
  longitude: number;
}

export const propertiesForBuy: any[] = [
  {
    id: "1001000100010088",
    name: "Sunny Apartment",
    title: "Apartment For Sale",
    description: "Spacious apartment in Downtown with modern amenities.",
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Unfurnished",
    constructionStatus: "Ready to move",
    listedBy: "John Doe",
    superBuiltUpArea: 1200,
    carpetArea: 1000,
    totalFloors: 15,
    floorNo: 5,
    carParking: 1,
    facing: "East",
    projectName: "Downtown Residency",
    price: 500000,
    postedDate: "2024-07-10",
    images: [image1, image2, image3],
    location: "Downtown, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.712776,
      longitude: -74.005974,
    },
    sellerDetails: {
      id: "seller-1001",
      fullName: "Alice Johnson",
      username: "alice_johnson",
      email: "alice.johnson@realestate.com",
      role: "Seller",
      propertiesListed: 15,
      contactNumber: "+1234567891",
      address: "456 Oak Avenue, Metropolis, NY, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.7,
      lastLogin: new Date("2024-07-20T10:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/alicejohnson",
        facebook: "https://facebook.com/alicejohnson",
      },
      preferredContactMethod: "phone",
      bio: "Experienced agent specializing in residential properties.",
      certifications: ["Certified Real Estate Agent"],
      createdAt: new Date("2023-11-01T09:00:00Z"),
      updatedAt: new Date("2024-07-22T09:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1002000200020002",
    name: "Cozy Cottage",
    title: "Apartment For Sale",
    description: "Charming cottage in a quiet suburban neighborhood.",
    type: "Independent House",
    bedrooms: 2,
    bathrooms: 1,
    furnishing: "Semi-Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Jane Smith",
    superBuiltUpArea: 900,
    carpetArea: 800,
    totalFloors: 1,
    floorNo: 0,
    carParking: 2,
    facing: "North",
    projectName: "Suburban Retreat",
    price: 350000,
    postedDate: "2024-06-20",
    images: [image1, image2, image3],
    location: "Suburbs, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.73061,
      longitude: -73.935242,
    },
    sellerDetails: {
      id: "seller-2004",
      fullName: "Sophia Wilson",
      username: "sophia_wilson",
      email: "sophia.wilson@realestate.com",
      role: "Seller",
      propertiesListed: 7,
      contactNumber: "+1234567804",
      address: "303 Oak Drive, Grandview, CO, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.8,
      lastLogin: new Date("2024-07-19T15:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/sophiawilson",
      },
      preferredContactMethod: "phone",
      bio: "Specializing in eco-friendly and sustainable properties.",
      certifications: ["Eco-Friendly Property Specialist"],
      firmName: "Wilson & Co.",
      createdAt: new Date("2023-11-20T13:00:00Z"),
      updatedAt: new Date("2024-07-22T12:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1003000330030003",
    name: "Luxury Villa",
    title: "Apartment For Sale",
    description:
      "Exquisite villa with luxurious amenities and panoramic views.",
    type: "Villa",
    bedrooms: 5,
    bathrooms: 5,
    furnishing: "Fully Furnished",
    constructionStatus: "Under Construction",
    listedBy: "Alice Johnson",
    superBuiltUpArea: 3000,
    carpetArea: 2500,
    totalFloors: 2,
    floorNo: 1,
    carParking: 4,
    facing: "South-East",
    projectName: "Hilltop Haven",
    price: 1200000,
    postedDate: "2024-07-01",
    images: [image1, image2, image3],
    location: "Uptown, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.748817,
      longitude: -73.985428,
    },
    sellerDetails: {
      id: "seller-2005",
      fullName: "Oliver Adams",
      username: "oliver_adams",
      email: "oliver.adams@realestate.com",
      role: "Seller",
      propertiesListed: 11,
      contactNumber: "+1234567805",
      address: "404 Birch Lane, Uptown, WA, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.5,
      lastLogin: new Date("2024-07-20T16:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/oliveradams",
        facebook: "https://facebook.com/oliveradams",
      },
      preferredContactMethod: "email",
      bio: "Expert in commercial and retail real estate.",
      certifications: ["Commercial Property Specialist"],
      firmName: "Adams Realty",
      createdAt: new Date("2024-02-10T14:00:00Z"),
      updatedAt: new Date("2024-07-22T13:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1004000400040004",
    name: "Modern Loft",
    title: "Apartment For Sale",
    description:
      "Stylish loft with contemporary design and city skyline views.",
    type: "Penthouse",
    bedrooms: 4,
    bathrooms: 3,
    furnishing: "Semi-Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Bob Brown",
    superBuiltUpArea: 1500,
    carpetArea: 1300,
    totalFloors: 20,
    floorNo: 15,
    carParking: 2,
    facing: "West",
    projectName: "Skyline Heights",
    price: 750000,
    postedDate: "2024-07-05",
    images: [image1, image2, image3],
    location: "Midtown, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.754932,
      longitude: -73.984016,
    },
    sellerDetails: {
      id: "seller-2006",
      fullName: "Emily Brown",
      username: "emily_brown",
      email: "emily.brown@realestate.com",
      role: "Seller",
      propertiesListed: 13,
      contactNumber: "+1234567806",
      address: "505 Cedar Street, Downtown, OR, USA",
      profilePicture: SellerProfileImage,
      verified: false,
      rating: 4.3,
      lastLogin: new Date("2024-07-21T12:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/emilybrown",
      },
      preferredContactMethod: "phone",
      bio: "Focused on residential and investment properties.",
      certifications: ["Investment Property Specialist"],
      firmName: "Brown Realty Group",
      createdAt: new Date("2024-04-05T09:00:00Z"),
      updatedAt: new Date("2024-07-22T14:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1003000500050005",
    name: "Beachside Bungalow",
    title: "Apartment For Sale",
    description:
      "Serene bungalow with beachfront access and scenic surroundings.",
    type: "Bungalow",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Unfurnished",
    constructionStatus: "Ready to move",
    listedBy: "Charlie Davis",
    superBuiltUpArea: 2000,
    carpetArea: 1800,
    totalFloors: 1,
    floorNo: 0,
    carParking: 3,
    facing: "South-West",
    projectName: "Beachside Retreat",
    price: 950000,
    postedDate: "2024-06-30",
    images: [image1, image2, image3],
    location: "Coastline, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.579021,
      longitude: -74.151535,
    },
    sellerDetails: {
      id: "seller-2001",
      fullName: "Michael Green",
      username: "michael_green",
      email: "michael.green@realestate.com",
      role: "Seller",
      propertiesListed: 22,
      contactNumber: "+1234567801",
      address: "909 Summit Avenue, New City, CA, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.6,
      lastLogin: new Date("2024-07-20T09:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/michaelgreen",
        facebook: "https://facebook.com/michaelgreen",
      },
      preferredContactMethod: "phone",
      bio: "Experienced in high-end residential properties.",
      certifications: ["Luxury Property Specialist"],
      firmName: "Green Realty",
      createdAt: new Date("2023-12-01T10:00:00Z"),
      updatedAt: new Date("2024-07-22T09:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1006000600060006",
    name: "Downtown Studio",
    title: "Apartment For Sale",
    description:
      "Compact studio in the heart of downtown with easy access to amenities.",
    type: "Studio Apartment",
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "Fully Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Emily Evans",
    superBuiltUpArea: 800,
    carpetArea: 600,
    totalFloors: 10,
    floorNo: 7,
    carParking: 1,
    facing: "North-East",
    projectName: "Downtown Towers",
    price: 450000,
    postedDate: "2024-07-07",
    images: [image1, image2, image3],
    location: "Downtown, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.707496,
      longitude: -74.011276,
    },
    sellerDetails: {
      id: "seller-2002",
      fullName: "Linda Scott",
      username: "linda_scott",
      email: "linda.scott@realestate.com",
      role: "Seller",
      propertiesListed: 14,
      contactNumber: "+1234567802",
      address: "1010 Coral Lane, Beachside, FL, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.7,
      lastLogin: new Date("2024-07-19T10:30:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/lindascott",
      },
      preferredContactMethod: "email",
      bio: "Specializes in beachfront and vacation properties.",
      certifications: ["Vacation Property Specialist"],
      firmName: "Scott Realty Group",
      createdAt: new Date("2024-01-05T12:00:00Z"),
      updatedAt: new Date("2024-07-22T10:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1001000100010001",
    name: "Sunny Apartment",
    title: "Apartment For Sale",
    description: "Spacious apartment in Downtown with modern amenities.",
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Unfurnished",
    constructionStatus: "Ready to move",
    listedBy: "John Doe",
    superBuiltUpArea: 1200,
    carpetArea: 1000,
    totalFloors: 15,
    floorNo: 5,
    carParking: 1,
    facing: "East",
    projectName: "Downtown Residency",
    price: 500000,
    postedDate: "2024-07-10",
    images: [image1, image2, image3],
    location: "Downtown, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.712776,
      longitude: -74.005974,
    },
    sellerDetails: {
      id: "seller-2003",
      fullName: "James Harris",
      username: "james_harris",
      email: "james.harris@realestate.com",
      role: "Seller",
      propertiesListed: 9,
      contactNumber: "+1234567803",
      address: "2020 Maple Street, Metroville, TX, USA",
      profilePicture: SellerProfileImage,
      verified: false,
      rating: 4.4,
      lastLogin: new Date("2024-07-18T14:00:00Z"),
      socialLinks: {
        facebook: "https://facebook.com/jamesharris",
      },
      preferredContactMethod: "email",
      bio: "Focused on residential and multi-family properties.",
      certifications: ["Residential Property Specialist"],
      firmName: "Harris Homes",
      createdAt: new Date("2024-03-15T11:00:00Z"),
      updatedAt: new Date("2024-07-22T11:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "2002000200020002",
    name: "Cozy Cottage",
    title: "Independent House For Sale",
    description: "Charming cottage in a quiet suburban neighborhood.",
    type: "Independent House",
    bedrooms: 2,
    bathrooms: 1,
    furnishing: "Semi-Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Jane Smith",
    superBuiltUpArea: 900,
    carpetArea: 800,
    totalFloors: 1,
    floorNo: 0,
    carParking: 2,
    facing: "North",
    projectName: "Suburban Retreat",
    price: 350000,
    postedDate: "2024-06-20",
    images: [image1, image2, image3],
    location: "Suburbs, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.73061,
      longitude: -73.935242,
    },
    sellerDetails: {
      id: "seller-2007",
      fullName: "Aiden Clark",
      username: "aiden_clark",
      email: "aiden.clark@realestate.com",
      role: "Seller",
      propertiesListed: 16,
      contactNumber: "+1234567807",
      address: "606 Elm Street, Eastside, NV, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.9,
      lastLogin: new Date("2024-07-22T09:00:00Z"),
      socialLinks: {
        facebook: "https://facebook.com/aidenclark",
        linkedin: "https://linkedin.com/in/aidenclark",
      },
      preferredContactMethod: "email",
      bio: "Specializing in high-end and luxury properties.",
      certifications: ["Luxury Property Specialist"],
      firmName: "Clark Real Estate",
      createdAt: new Date("2024-03-15T10:00:00Z"),
      updatedAt: new Date("2024-07-22T15:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1003000300030003",
    name: "Luxury Villa",
    title: "Villa For Sale",
    description:
      "Exquisite villa with luxurious amenities and panoramic views.",
    type: "Villa",
    bedrooms: 5,
    bathrooms: 5,
    furnishing: "Fully Furnished",
    constructionStatus: "Under Construction",
    listedBy: "Alice Johnson",
    superBuiltUpArea: 3000,
    carpetArea: 2500,
    totalFloors: 2,
    floorNo: 1,
    carParking: 4,
    facing: "South-East",
    projectName: "Hilltop Haven",
    price: 1200000,
    postedDate: "2024-07-01",
    images: [image1, image2, image3],
    location: "Uptown, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.748817,
      longitude: -73.985428,
    },
    sellerDetails: {
      id: "seller-2008",
      fullName: "Mia Lewis",
      username: "mia_lewis",
      email: "mia.lewis@realestate.com",
      role: "Seller",
      propertiesListed: 9,
      contactNumber: "+1234567808",
      address: "707 Pine Street, Hillcrest, PA, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.4,
      lastLogin: new Date("2024-07-19T17:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/mialewis",
      },
      preferredContactMethod: "phone",
      bio: "Experienced in both residential and commercial properties.",
      certifications: ["Residential Property Specialist"],
      firmName: "Lewis Realty",
      createdAt: new Date("2024-01-20T11:00:00Z"),
      updatedAt: new Date("2024-07-22T16:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1004000400040056",
    name: "Modern Loft",
    title: "Penthouse For Sale",
    description:
      "Stylish loft with contemporary design and city skyline views.",
    type: "Penthouse",
    bedrooms: 4,
    bathrooms: 3,
    furnishing: "Semi-Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Bob Brown",
    superBuiltUpArea: 1500,
    carpetArea: 1300,
    totalFloors: 20,
    floorNo: 15,
    carParking: 2,
    facing: "West",
    projectName: "Skyline Heights",
    price: 750000,
    postedDate: "2024-07-05",
    images: [image1, image2, image3],
    location: "Midtown, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.754932,
      longitude: -73.984016,
    },
    sellerDetails: {
      id: "seller-2009",
      fullName: "Noah Martin",
      username: "noah_martin",
      email: "noah.martin@realestate.com",
      role: "Seller",
      propertiesListed: 5,
      contactNumber: "+1234567809",
      address: "808 Birch Lane, Downtown, TX, USA",
      profilePicture: SellerProfileImage,
      verified: false,
      rating: 4.2,
      lastLogin: new Date("2024-07-18T13:30:00Z"),
      socialLinks: {
        facebook: "https://facebook.com/noahmartin",
      },
      preferredContactMethod: "email",
      bio: "Specializes in first-time homebuyers and new developments.",
      certifications: ["New Development Specialist"],
      firmName: "Martin Realty",
      createdAt: new Date("2024-02-10T08:00:00Z"),
      updatedAt: new Date("2024-07-22T17:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1005000500050005",
    name: "Beachside Bungalow",
    title: "Bungalow For Sale",
    description:
      "Serene bungalow with beachfront access and scenic surroundings.",
    type: "Bungalow",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Unfurnished",
    constructionStatus: "Ready to move",
    listedBy: "Charlie Davis",
    superBuiltUpArea: 2000,
    carpetArea: 1800,
    totalFloors: 1,
    floorNo: 0,
    carParking: 3,
    facing: "South-West",
    projectName: "Beachside Retreat",
    price: 950000,
    postedDate: "2024-06-30",
    images: [image1, image2, image3],
    location: "Coastline, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.579021,
      longitude: -74.151535,
    },
    sellerDetails: {
      id: "seller-2010",
      fullName: "Olivia Turner",
      username: "olivia_turner",
      email: "olivia.turner@realestate.com",
      role: "Seller",
      propertiesListed: 17,
      contactNumber: "+1234567810",
      address: "909 Walnut Street, Lakeside, MI, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.7,
      lastLogin: new Date("2024-07-21T11:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/oliviaturner",
        facebook: "https://facebook.com/oliviaturner",
      },
      preferredContactMethod: "phone",
      bio: "Expert in luxury estates and high-value properties.",
      certifications: ["Luxury Property Specialist"],
      firmName: "Turner Realty",
      createdAt: new Date("2024-03-25T12:00:00Z"),
      updatedAt: new Date("2024-07-22T18:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1006000600090006",
    name: "Downtown Studio",
    title: "Studio Apartment For Sale",
    description:
      "Compact studio in the heart of downtown with easy access to amenities.",
    type: "Studio Apartment",
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "Fully Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Emily Evans",
    superBuiltUpArea: 800,
    carpetArea: 600,
    totalFloors: 10,
    floorNo: 7,
    carParking: 1,
    facing: "North-East",
    projectName: "Downtown Towers",
    price: 450000,
    postedDate: "2024-07-07",
    images: [image1, image2, image3],
    location: "Downtown, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.707496,
      longitude: -74.011276,
    },
    sellerDetails: {
      id: "seller-2014",
      fullName: "Ava Johnson",
      username: "ava_johnson",
      email: "ava.johnson@realestate.com",
      role: "Seller",
      propertiesListed: 11,
      contactNumber: "+1234567814",
      address: "4000 Willow Street, Greenfield, IL, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.5,
      lastLogin: new Date("2024-07-22T08:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/avajohnson",
      },
      preferredContactMethod: "phone",
      bio: "Focused on residential homes and suburban properties.",
      certifications: ["Residential Property Specialist"],
      firmName: "Johnson Realty",
      createdAt: new Date("2024-02-20T09:00:00Z"),
      updatedAt: new Date("2024-07-22T22:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1007000700070007",
    name: "Urban Condo",
    title: "Condo For Sale",
    description: "Modern condo with urban lifestyle and amenities.",
    type: "Condo",
    bedrooms: 2,
    bathrooms: 2,
    furnishing: "Semi-Furnished",
    constructionStatus: "Ready to move",
    listedBy: "David Clark",
    superBuiltUpArea: 1000,
    carpetArea: 850,
    totalFloors: 12,
    floorNo: 8,
    carParking: 1,
    facing: "South",
    projectName: "Urban Living Complex",
    price: 600000,
    postedDate: "2024-07-12",
    images: [image1, image2, image3],
    location: "City Center, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.743798,
      longitude: -73.992298,
    },
    sellerDetails: {
      id: "seller-2013",
      fullName: "Liam Roberts",
      username: "liam_roberts",
      email: "liam.roberts@realestate.com",
      role: "Seller",
      propertiesListed: 6,
      contactNumber: "+1234567813",
      address: "3000 Cedar Lane, Westfield, VA, USA",
      profilePicture: SellerProfileImage,
      verified: false,
      rating: 4.2,
      lastLogin: new Date("2024-07-20T16:30:00Z"),
      socialLinks: {
        facebook: "https://facebook.com/liamroberts",
      },
      preferredContactMethod: "email",
      bio: "Specializes in investment and rental properties.",
      certifications: ["Rental Property Specialist"],
      firmName: "Roberts Realty",
      createdAt: new Date("2024-07-01T10:00:00Z"),
      updatedAt: new Date("2024-07-22T21:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1008000800080008",
    name: "Suburban House",
    title: "House For Sale",
    description: "Cozy house in a peaceful suburban area.",
    type: "House",
    bedrooms: 3,
    bathrooms: 2,
    furnishing: "Unfurnished",
    constructionStatus: "Ready to move",
    listedBy: "Susan Lee",
    superBuiltUpArea: 1400,
    carpetArea: 1200,
    totalFloors: 2,
    floorNo: 1,
    carParking: 2,
    facing: "West",
    projectName: "Suburban Bliss",
    price: 550000,
    postedDate: "2024-06-25",
    images: [image1, image2, image3],
    location: "Suburbs, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.721776,
      longitude: -73.965974,
    },
    sellerDetails: {
      id: "seller-2012",
      fullName: "Emma Clark",
      username: "emma_clark",
      email: "emma.clark@realestate.com",
      role: "Seller",
      propertiesListed: 10,
      contactNumber: "+1234567812",
      address: "2000 Pine Avenue, Northside, WA, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.8,
      lastLogin: new Date("2024-07-21T14:00:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/emmaclark",
      },
      preferredContactMethod: "phone",
      bio: "Experienced in luxury apartments and urban properties.",
      certifications: ["Urban Property Specialist"],
      firmName: "Clark & Associates",
      createdAt: new Date("2024-06-15T11:00:00Z"),
      updatedAt: new Date("2024-07-22T20:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1009000900090009",
    name: "Countryside Farmhouse",
    title: "Farmhouse For Sale",
    description: "Beautiful farmhouse with ample land and scenic views.",
    type: "Farmhouse",
    bedrooms: 4,
    bathrooms: 3,
    furnishing: "Fully Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Mike Johnson",
    superBuiltUpArea: 2000,
    carpetArea: 1800,
    totalFloors: 1,
    floorNo: 0,
    carParking: 3,
    facing: "East",
    projectName: "Countryside Retreat",
    price: 700000,
    postedDate: "2024-06-15",
    images: [image1, image2, image3],
    location: "Countryside, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.762776,
      longitude: -73.975974,
    },
    sellerDetails: {
      id: "seller-2011",
      fullName: "James Walker",
      username: "james_walker",
      email: "james.walker@realestate.com",
      role: "Seller",
      propertiesListed: 8,
      contactNumber: "+1234567811",
      address: "1000 Elm Street, Rivertown, KY, USA",
      profilePicture: SellerProfileImage,
      verified: true,
      rating: 4.6,
      lastLogin: new Date("2024-07-22T10:30:00Z"),
      socialLinks: {
        linkedin: "https://linkedin.com/in/jameswalker",
      },
      preferredContactMethod: "email",
      bio: "Specializing in rural and agricultural properties.",
      certifications: ["Agricultural Property Specialist"],
      firmName: "Walker Real Estate",
      createdAt: new Date("2024-05-01T09:00:00Z"),
      updatedAt: new Date("2024-07-22T19:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
  {
    id: "1010001000100010",
    name: "Mountain Cabin",
    title: "Cabin For Sale",
    description: "Rustic cabin with mountain views and serene surroundings.",
    type: "Cabin",
    bedrooms: 2,
    bathrooms: 1,
    furnishing: "Fully Furnished",
    constructionStatus: "Ready to move",
    listedBy: "Linda White",
    superBuiltUpArea: 800,
    carpetArea: 700,
    totalFloors: 1,
    floorNo: 0,
    carParking: 1,
    facing: "North",
    projectName: "Mountain Retreat",
    price: 300000,
    postedDate: "2024-06-05",
    images: [image1, image2, image3],
    location: "Mountains, Cityville",
    isFavorite: false,
    locationCoordinates: {
      latitude: 40.782776,
      longitude: -73.995974,
    },
    sellerDetails: {
      id: "seller-2013",
      fullName: "Liam Roberts",
      username: "liam_roberts",
      email: "liam.roberts@realestate.com",
      role: "Seller",
      propertiesListed: 6,
      contactNumber: "+1234567813",
      address: "3000 Cedar Lane, Westfield, VA, USA",
      profilePicture: SellerProfileImage,
      verified: false,
      rating: 4.2,
      lastLogin: new Date("2024-07-20T16:30:00Z"),
      socialLinks: {
        facebook: "https://facebook.com/liamroberts",
      },
      preferredContactMethod: "email",
      bio: "Specializes in investment and rental properties.",
      certifications: ["Rental Property Specialist"],
      firmName: "Roberts Realty",
      createdAt: new Date("2024-07-01T10:00:00Z"),
      updatedAt: new Date("2024-07-22T21:00:00Z"),
    },
    reviews: [
      {
        id: "review1001",
        reviewerName: "Alice Williams",
        dateTime: "2024-07-10T14:30:00",
        rating: 4.5,
        description:
          "Great property with modern amenities. The neighborhood is quiet and well-connected to the city.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1002",
        reviewerName: "Bob Johnson",
        dateTime: "2024-07-12T09:45:00",
        rating: 4.0,
        description:
          "Spacious apartment with a beautiful view. The interior design is elegant and contemporary.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1003",
        reviewerName: "Charlie Davis",
        dateTime: "2024-07-14T18:15:00",
        rating: 3.5,
        description:
          "Good location and decent facilities. However, some maintenance work is needed.",
        image: "https://via.placeholder.com/100x100",
      },
      {
        id: "review1004",
        reviewerName: "Dana Lee",
        dateTime: "2024-07-16T13:00:00",
        rating: 5.0,
        description:
          "Excellent property with luxurious amenities. The surroundings are serene and the view is breathtaking.",
        image: "https://via.placeholder.com/100x100",
      },
    ],
  },
];
